#! /usr/bin/env python
## encoding: utf-8

import sys

def options(opt):
    opt.load('compiler_cxx')

def configure(ctx):
    ctx.load('compiler_cxx')
    if linux():
        if not ctx.env['LIB_PTHREAD']:
            ctx.check_cxx(lib='pthread')

def build(bld):
    use_flags = []
    if linux():
        use_flags += ['PTHREAD']
    bld.stlib(
        source='fused-src/gtest/gtest-all.cc', 
        includes='fused-src', 
        use=use_flags,
        target='gtest')

def linux():
    return sys.platform == 'linux2'
